package com.screw.erp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrders<M extends BaseOrders<M>> extends Model<M> implements IBean {

	public void setOid(java.lang.Integer oid) {
		set("oid", oid);
	}
	
	public java.lang.Integer getOid() {
		return getInt("oid");
	}

	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public void setTotalPrice(java.lang.Float totalPrice) {
		set("totalPrice", totalPrice);
	}
	
	public java.lang.Float getTotalPrice() {
		return getFloat("totalPrice");
	}

	public void setCreateTime(java.util.Date createTime) {
		set("createTime", createTime);
	}
	
	public java.util.Date getCreateTime() {
		return get("createTime");
	}

	public void setPayTime(java.util.Date payTime) {
		set("payTime", payTime);
	}
	
	public java.util.Date getPayTime() {
		return get("payTime");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
