package com.screw.erp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseScrew<M extends BaseScrew<M>> extends Model<M> implements IBean {

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}
	
	public java.lang.Integer getSid() {
		return getInt("sid");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setSpec(java.lang.String spec) {
		set("spec", spec);
	}
	
	public java.lang.String getSpec() {
		return getStr("spec");
	}

	public void setThousandPerPrice(java.lang.Float thousandPerPrice) {
		set("thousandPerPrice", thousandPerPrice);
	}
	
	public java.lang.Float getThousandPerPrice() {
		return getFloat("thousandPerPrice");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
