package com.screw.erp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOrderitem<M extends BaseOrderitem<M>> extends Model<M> implements IBean {

	public void setOrderItemId(java.lang.Integer orderItemId) {
		set("orderItemId", orderItemId);
	}
	
	public java.lang.Integer getOrderItemId() {
		return getInt("orderItemId");
	}

	public void setOid(java.lang.Integer oid) {
		set("oid", oid);
	}
	
	public java.lang.Integer getOid() {
		return getInt("oid");
	}

	public void setSid(java.lang.Integer sid) {
		set("sid", sid);
	}
	
	public java.lang.Integer getSid() {
		return getInt("sid");
	}

	public void setNumber(java.lang.Integer number) {
		set("number", number);
	}
	
	public java.lang.Integer getNumber() {
		return getInt("number");
	}

	public void setItemPrice(java.lang.Float itemPrice) {
		set("itemPrice", itemPrice);
	}
	
	public java.lang.Float getItemPrice() {
		return getFloat("itemPrice");
	}

}
