package com.screw.erp.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBuyer<M extends BaseBuyer<M>> extends Model<M> implements IBean {

	public void setBid(java.lang.Integer bid) {
		set("bid", bid);
	}
	
	public java.lang.Integer getBid() {
		return getInt("bid");
	}

	public void setBuyerName(java.lang.String buyerName) {
		set("buyerName", buyerName);
	}
	
	public java.lang.String getBuyerName() {
		return getStr("buyerName");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setMobile(java.lang.String mobile) {
		set("mobile", mobile);
	}
	
	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
