package com.screw.erp.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("buyer", "bid", Buyer.class);
		arp.addMapping("orderitem", "orderItemId", Orderitem.class);
		arp.addMapping("orders", "oid", Orders.class);
		arp.addMapping("screw", "sid", Screw.class);
		arp.addMapping("user", "id", User.class);
	}
}

