package com.screw.erp.model;

import com.screw.erp.model.base.BaseAccountRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AccountRole extends BaseAccountRole<AccountRole> {
	
}
