package com.screw.erp.model;

import com.screw.erp.model.base.BaseAccount;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Account extends BaseAccount<Account>{
    public static final  int STATUS_LOCKED=-1;
     public static final int STATUS_OK=1;

    public static final Account dao=new Account().dao();
    public  boolean isStatusOk(){
        return this.getStatus()==STATUS_OK;
    }

}
