package com.screw.erp.model;

import com.screw.erp.model.base.BaseOrderitem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Orderitem extends BaseOrderitem<Orderitem> {
	
}
